### ISSUE TITLE
Issue with \{cases}

### ISSUE THREAD

**Issue by jiotv321** [roniemartinez/latex2mathml#391] opened 2023-04-27 20:15 UTC
Hi first of all thanks for making this wonderful module.

I have LaTex  bellow

`f\left(x\right)= \begin{cases} \frac{1-e^{3x-12}}{20\ln{(5-x)}} ; x≤4 \\ \frac{x^3-16x^2+83x+k}{x^3-21x^2+140x-288}; x>4 \end {cases}`

While trying to convert this with latex2mathml it gives 

> latex2mathml.exceptions.MissingEndError

But when trying to convert with https://temml.org/ it is giving a valid mathml and doesn't showing error.

Can you help me to overcome this issue in python?

**Comment by roniemartinez** [comment] 2023-05-06 22:57
@jiotv321 The issue is because there is a space between `\end {cases}`. It should be fixed in https://github.com/roniemartinez/latex2mathml/pull/393

**Comment by roniemartinez** [comment] 2023-05-06 22:59
@all-contributors please add @jiotv321  for bug

**Closed** 2023-05-06 23:02 UTC
Labels: bug
